"""Initial migration - create all tables

Revision ID: 0e405697b042
Revises:
Create Date: 2026-02-01 18:14:59.719676+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

# revision identifiers, used by Alembic.
revision: str = "0e405697b042"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abilities",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parameters_schema", JSONB(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_abilities_type"), "abilities", ["type"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("cognito_id", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_cognito_id"), "users", ["cognito_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "team",
            sa.Enum("VILLAGE", "WEREWOLF", "VAMPIRE", "ALIEN", "NEUTRAL", name="team"),
            nullable=False,
        ),
        sa.Column("wake_order", sa.Integer(), nullable=True),
        sa.Column("wake_target", sa.String(length=50), nullable=True),
        sa.Column("votes", sa.Integer(), nullable=False),
        sa.Column("creator_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "PUBLIC", "OFFICIAL", name="visibility"),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("vote_score", sa.Integer(), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_creator_id"), "roles", ["creator_id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_index(op.f("ix_roles_team"), "roles", ["team"], unique=False)
    op.create_index(op.f("ix_roles_visibility"), "roles", ["visibility"], unique=False)
    op.create_index(op.f("ix_roles_vote_score"), "roles", ["vote_score"], unique=False)
    op.create_table(
        "ability_steps",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("role_id", UUID(as_uuid=True), nullable=False),
        sa.Column("ability_id", UUID(as_uuid=True), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "modifier",
            sa.Enum("NONE", "AND", "OR", "IF", name="stepmodifier"),
            nullable=False,
        ),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("parameters", JSONB(), nullable=False),
        sa.Column("condition_type", sa.String(length=50), nullable=True),
        sa.Column("condition_params", JSONB(), nullable=True),
        sa.ForeignKeyConstraint(["ability_id"], ["abilities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ability_steps_ability_id"),
        "ability_steps",
        ["ability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ability_steps_role_id"), "ability_steps", ["role_id"], unique=False
    )
    op.create_table(
        "win_conditions",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("role_id", UUID(as_uuid=True), nullable=False),
        sa.Column("condition_type", sa.String(length=50), nullable=False),
        sa.Column("condition_params", JSONB(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("overrides_team", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_win_conditions_role_id"), "win_conditions", ["role_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_win_conditions_role_id"), table_name="win_conditions")
    op.drop_table("win_conditions")
    op.drop_index(op.f("ix_ability_steps_role_id"), table_name="ability_steps")
    op.drop_index(op.f("ix_ability_steps_ability_id"), table_name="ability_steps")
    op.drop_table("ability_steps")
    op.drop_index(op.f("ix_roles_vote_score"), table_name="roles")
    op.drop_index(op.f("ix_roles_visibility"), table_name="roles")
    op.drop_index(op.f("ix_roles_team"), table_name="roles")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_creator_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_cognito_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_abilities_type"), table_name="abilities")
    op.drop_table("abilities")
    # ### end Alembic commands ###
